import type {
  ClinicalAlert,
  Device,
  Patient,
  Recording,
} from "@/types/clinical";

const cycles = [
  ["Crackles", 94],
  ["Crackles + Wheezes", 91],
  ["Wheezes", 89],
  ["Normal", 96],
  ["Crackles", 92],
  ["Crackles + Wheezes", 90],
  ["Normal", 95],
  ["Wheezes", 88],
] as const;

export const recordings: Recording[] = [
  {
    id: "REC-001",
    patientId: "PAT-001",
    patientName: "Trần Văn Mạnh",
    patientCode: "PAT-001",
    recordedAt: "27/09/2026 · 15:30",
    duration: 24.6,
    classification: "Crackles + Wheezes",
    confidence: 92,
    status: "pending_review",
    deviceId: "STETHO-001",
    cycles: cycles.map((c, i) => ({
      id: `c${i + 1}`,
      number: i + 1,
      start: +(i * 3.05).toFixed(1),
      end: +((i + 1) * 3.05).toFixed(1),
      classification: c[0],
      confidence: c[1],
    })),
  },
  {
    id: "REC-002",
    patientId: "PAT-002",
    patientName: "Phạm Đức Thành",
    patientCode: "PAT-002",
    recordedAt: "27/09/2026 · 14:10",
    duration: 21.8,
    classification: "Crackles",
    confidence: 88,
    status: "pending_review",
    deviceId: "STETHO-002",
    cycles: cycles
      .slice(0, 7)
      .map((c, i) => ({
        id: `c${i + 1}`,
        number: i + 1,
        start: +(i * 3.1).toFixed(1),
        end: +((i + 1) * 3.1).toFixed(1),
        classification: i % 3 ? c[0] : "Crackles",
        confidence: c[1],
      })),
  },
  {
    id: "REC-003",
    patientId: "PAT-003",
    patientName: "Đỗ Hữu Trí",
    patientCode: "PAT-003",
    recordedAt: "27/09/2026 · 12:00",
    duration: 23.5,
    classification: "Wheezes",
    confidence: 90,
    status: "confirmed",
    deviceId: "STETHO-003",
    cycles: cycles.map((c, i) => ({
      id: `c${i + 1}`,
      number: i + 1,
      start: +(i * 2.9).toFixed(1),
      end: +((i + 1) * 2.9).toFixed(1),
      classification: i % 4 === 3 ? "Normal" : "Wheezes",
      confidence: c[1],
    })),
    note: "Tiếng thở rít nhẹ thì thở ra; tiếp tục theo dõi.",
  },
  {
    id: "REC-004",
    patientId: "PAT-004",
    patientName: "Nguyễn Thị Lan",
    patientCode: "PAT-004",
    recordedAt: "27/09/2026 · 09:20",
    duration: 22,
    classification: "Crackles",
    confidence: 84,
    status: "pending_review",
    deviceId: "STETHO-001",
    cycles: cycles
      .slice(0, 7)
      .map((c, i) => ({
        id: `c${i + 1}`,
        number: i + 1,
        start: +(i * 3.1).toFixed(1),
        end: +((i + 1) * 3.1).toFixed(1),
        classification: i % 3 === 2 ? "Normal" : "Crackles",
        confidence: c[1],
      })),
  },
  {
    id: "REC-005",
    patientId: "PAT-005",
    patientName: "Lê Minh Tuấn",
    patientCode: "PAT-005",
    recordedAt: "26/09/2026 · 16:45",
    duration: 25,
    classification: "Normal",
    confidence: 95,
    status: "confirmed",
    deviceId: "STETHO-002",
    cycles: cycles.map((c, i) => ({
      id: `c${i + 1}`,
      number: i + 1,
      start: +(i * 3.1).toFixed(1),
      end: +((i + 1) * 3.1).toFixed(1),
      classification: "Normal",
      confidence: Math.max(92, c[1]),
    })),
  },
];

export const patients: Patient[] = [
  {
    id: "PAT-001",
    code: "PAT-001",
    name: "Trần Văn Mạnh",
    age: 64,
    gender: "Nam",
    phone: "090 123 4567",
    diagnosis: "COPD",
    spo2: 89,
    sound: "Crackles + Wheezes",
    confidence: 92,
    needsAttention: true,
    visits: [
      {
        id: "VIS-001",
        patientId: "PAT-001",
        startedAt: "27/09/2026 · 15:20",
        doctor: "BS. Nguyễn Bảo Nguyên",
        spo2: 89,
        status: "completed",
        recordingId: "REC-001",
        result: "Crackles + Wheezes",
        note: "Theo dõi SpO₂, cân nhắc hỗ trợ oxy nếu dưới 88%.",
      },
      {
        id: "VIS-000",
        patientId: "PAT-001",
        startedAt: "26/09/2026 · 09:15",
        doctor: "BS. Nguyễn Bảo Nguyên",
        spo2: 93,
        status: "completed",
        result: "Crackles",
      },
    ],
  },
  {
    id: "PAT-002",
    code: "PAT-002",
    name: "Phạm Đức Thành",
    age: 58,
    gender: "Nam",
    phone: "091 456 8899",
    diagnosis: "Hen phế quản",
    spo2: 91,
    sound: "Crackles",
    confidence: 88,
    needsAttention: true,
    visits: [
      {
        id: "VIS-002",
        patientId: "PAT-002",
        startedAt: "27/09/2026 · 14:00",
        doctor: "BS. Nguyễn Bảo Nguyên",
        spo2: 91,
        status: "completed",
        recordingId: "REC-002",
        result: "Crackles",
      },
    ],
  },
  {
    id: "PAT-003",
    code: "PAT-003",
    name: "Đỗ Hữu Trí",
    age: 47,
    gender: "Nam",
    phone: "098 221 1212",
    diagnosis: "Hen phế quản",
    spo2: 95,
    sound: "Wheezes",
    confidence: 90,
    needsAttention: true,
    visits: [
      {
        id: "VIS-003",
        patientId: "PAT-003",
        startedAt: "27/09/2026 · 11:50",
        doctor: "BS. Nguyễn Bảo Nguyên",
        spo2: 95,
        status: "completed",
        recordingId: "REC-003",
        result: "Wheezes",
      },
    ],
  },
  {
    id: "PAT-004",
    code: "PAT-004",
    name: "Nguyễn Thị Lan",
    age: 72,
    gender: "Nữ",
    phone: "093 510 9288",
    diagnosis: "Viêm phổi cộng đồng",
    spo2: 92,
    sound: "Crackles",
    confidence: 84,
    needsAttention: true,
    visits: [
      {
        id: "VIS-004",
        patientId: "PAT-004",
        startedAt: "27/09/2026 · 09:10",
        doctor: "BS. Nguyễn Bảo Nguyên",
        spo2: 92,
        status: "completed",
        recordingId: "REC-004",
        result: "Crackles",
      },
    ],
  },
  {
    id: "PAT-005",
    code: "PAT-005",
    name: "Lê Minh Tuấn",
    age: 39,
    gender: "Nam",
    phone: "097 613 7788",
    diagnosis: "Theo dõi sau viêm phế quản",
    spo2: 97,
    sound: "Normal",
    confidence: 95,
    needsAttention: false,
    visits: [
      {
        id: "VIS-005",
        patientId: "PAT-005",
        startedAt: "26/09/2026 · 16:35",
        doctor: "BS. Nguyễn Bảo Nguyên",
        spo2: 97,
        status: "completed",
        recordingId: "REC-005",
        result: "Normal",
      },
    ],
  },
  {
    id: "PAT-006",
    code: "PAT-006",
    name: "Võ Thị Hương",
    age: 51,
    gender: "Nữ",
    phone: "090 334 5522",
    diagnosis: "Theo dõi khó thở",
    spo2: 96,
    sound: "Normal",
    confidence: 94,
    needsAttention: false,
    visits: [],
  },
];

export const alerts: ClinicalAlert[] = [
  {
    id: "A1",
    patientId: "PAT-001",
    patientName: "Trần Văn Mạnh",
    patientCode: "PAT-001",
    type: "spo2",
    message: "SpO₂ giảm xuống 89% — cần đánh giá lâm sàng",
    time: "5 phút trước",
    severity: "critical",
    unread: true,
  },
  {
    id: "A2",
    patientId: "PAT-001",
    patientName: "Trần Văn Mạnh",
    patientCode: "PAT-001",
    type: "sound",
    message: "AI phát hiện Crackles + Wheezes",
    time: "12 phút trước",
    severity: "warning",
    unread: true,
  },
  {
    id: "A3",
    patientId: "PAT-004",
    patientName: "Nguyễn Thị Lan",
    patientCode: "PAT-004",
    type: "review",
    message: "Bản ghi âm mới đang chờ bác sĩ xác nhận",
    time: "1 giờ trước",
    severity: "info",
    unread: true,
  },
  {
    id: "A4",
    type: "device",
    message: "Thiết bị SPO2-004 đã mất kết nối",
    time: "2 giờ trước",
    severity: "warning",
    unread: false,
  },
];

export const devices: Device[] = [
  {
    id: "STETHO-001",
    type: "stetho",
    patientId: "PAT-001",
    patientName: "Trần Văn Mạnh",
    online: true,
    battery: 82,
    lastActive: "Vừa xong",
    firmware: "v2.4.1",
  },
  {
    id: "STETHO-002",
    type: "stetho",
    patientId: "PAT-002",
    patientName: "Phạm Đức Thành",
    online: true,
    battery: 64,
    lastActive: "12 phút trước",
    firmware: "v2.4.1",
  },
  {
    id: "STETHO-003",
    type: "stetho",
    patientId: "PAT-003",
    patientName: "Đỗ Hữu Trí",
    online: true,
    battery: 91,
    lastActive: "1 giờ trước",
    firmware: "v2.4.0",
  },
  {
    id: "SPO2-001",
    type: "spo2",
    patientId: "PAT-001",
    patientName: "Trần Văn Mạnh",
    online: true,
    battery: 76,
    lastActive: "Đang truyền dữ liệu",
    firmware: "v1.8.2",
  },
  {
    id: "SPO2-004",
    type: "spo2",
    patientId: "PAT-004",
    patientName: "Nguyễn Thị Lan",
    online: false,
    battery: 18,
    lastActive: "2 giờ trước",
    firmware: "v1.8.1",
  },
];

export const doctor = {
  name: "BS. Nguyễn Bảo Nguyên",
  email: "bao.nguyen@respicare.med.vn",
  department: "Khoa Hô hấp · AIoT",
  hospital: "Bệnh viện Đa khoa Trung tâm",
};
